{{ config(materialized='view') }}

with covid as (
SELECT 
NOTIFICATION_DATE
,LHD_2010_CODE
,LHD_2010_NAME
,LGA_CODE_19
,LGA_NAME_19
,CONFIRMED_CASES_COUNT
,CASE WHEN postcode = 'None' THEN 'NULL' ELSE postcode END as postcode
FROM MODERN_DATA_STACK.GOOGLE_SHEETS.COVID_CASES
WHERE POSTCODE is Not null 
)
select * FROM covid