{{ config(materialized='view') }}

with covid as (
SELECT 
NOTIFICATION_DATE,POSTCODE,LHD_2010_CODE,LHD_2010_NAME,LGA_CODE19,LGA_NAME19,CONFIRMED_CASES_COUNT
FROM FIVETRAN_DATABASE.FUEL_PRICE.COVID_CASE
)
select * FROM covid